# Generated by Django 4.2.3 on 2024-12-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(max_length=255)),
                ("ano_publicacao", models.IntegerField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
    ]
